management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

info:
  application:
    name: product-ms
    description: Product Microservice of Delivery Application
    author: Dan Vega
    version: '@project.version@'
spring:
  profiles:
    active: prod